project_id = "yfltlcwogdnvilhvsnjw"

[functions.get-maptiler-key]
verify_jwt = false

[functions.locations]
verify_jwt = false

[functions.live-locations]
verify_jwt = false

[functions.auth]
verify_jwt = false
